### ISSUE TITLE
Error "KeyError: file" and "Unsupported ziptree entry type: hidden"

### ISSUE THREAD

**Issue by shimamura-sakura** [bhrevol/dlsite-async#136]
OS and Python: ArchLinux, Python 3.11.8
Version: 0.3.0
What have I done: use the "Download web-optimized images from a manga/comic work to the current working directory" example to download RJ084250
code:
```python
import os
import asyncio
from dlsite_async import PlayAPI

username = 'usernamehere'
password = 'passwordhere'

async def f():
    async with PlayAPI(trust_env=True) as play_api:
        await play_api.login(username, password)
        token = await play_api.download_token("RJ084250")
        tree = await play_api.ziptree(token)
        for filename, playfile in tree.items():
            if playfile.type != "image":
                continue
            orig_path, _ = os.path.splitext(filename)
            _, ext = os.path.splitext(playfile.optimized_name)
            dest = f"{orig_path}{ext}"
            await play_api.download_playfile(
                token, playfile, dest, mkdir=True, descramble=True
            )
asyncio.run(f())

```
What did I expect to see: It report no error and downlod the files
What did I see instead:

### First, it reported this error:
```
Traceback (most recent call last):
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 198, in from_json
    playfile = {
               ^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 199, in <dictcomp>
    key: PlayFile.from_json(value)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 121, in from_json
    files = data[type_]
            ~~~~^^^^^^^
KeyError: 'file'
```
I fixed this by making the following change in `play/modles.py PlayFile.from_json`
```python
- files = data[type_]
+ files = data.get(type_, {})
```
### Then, it reported this error:
```
Traceback (most recent call last):
  File "/home/jerry/Programming/2024-4/py-usedlsite/dl.py", line 23, in <module>
    asyncio.run(f())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jerry/Programming/2024-4/py-usedlsite/dl.py", line 13, in f
    tree = await play_api.ziptree(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/api.py", line 55, in ziptree
    return ZipTree.from_json(await response.json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 202, in from_json
    tree = [_tree_entry(entry) for entry in data.get("tree", [])]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 202, in <listcomp>
    tree = [_tree_entry(entry) for entry in data.get("tree", [])]
            ^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 162, in _tree_entry
    return _TreeFolder.from_json(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 151, in from_json
    children = [_tree_entry(entry) for entry in data.get("children", [])]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 151, in <listcomp>
    children = [_tree_entry(entry) for entry in data.get("children", [])]
                ^^^^^^^^^^^^^^^^^^
  File "/home/jerry/my_venv/lib/python3.11/site-packages/dlsite_async/play/models.py", line 163, in _tree_entry
    raise DlsiteError(  # pragma: no cover
dlsite_async.exceptions.DlsiteError: Unsupported ziptree entry type: hidden
```
I fixed this by adding this code to `play/models.py _tree_entry()`
```python
if data["type"] == "hidden":
    return None
```
### Other
Also, I think this line can be improved to create all parent directories `play/api.py PlayAPI.download_playfile()`
```python
- dest.parent.mkdir()
+ dest.parent.mkdir(parents=True)
```

**Comment by bhrevol** [comment]
Thanks for catching this, it should be fixed in the latest release (0.4.1). I had not seen any works with the `hidden` ziptree entries before. Newer `.dlst` works don't use the hidden entries, so it looks like they must have changed the ziptree format at some point.
